### ISSUE TITLE
Loading fonts image via VkImageHelper.loadImageFromFile(...) causes error output in console

### ISSUE THREAD

**Issue by aromanelli** [fynnfluegge/oreon-engine#38]
The following error appears on the console when starting up VkOreonworlds.  Specifically, when line 133 in VkGUI.java makes a call to VkImageHelper.loadImageFromFile(...) ...

> ERROR OCCURED: Object: 0x7ff8c8826cc8 (Type = 6) | vkCmdPipelineBarrier(): dstStageMask flag VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT is not compatible with the queue family properties of this command buffer. The spec valid usage text states 'Any pipeline stage included in srcStageMask or dstStageMask must be supported by the capabilities of the queue family specified by the queueFamilyIndex member of the VkCommandPoolCreateInfo structure that was used to create the VkCommandPool that commandBuffer was allocated from, as specified in the table of supported pipeline stages.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdPipelineBarrier-srcStageMask-01183)

The above error is outputted to the console when method vkCmdPipelineBarrier(...), at line 390, in CommandBuffer, is called.  See attached screenshots for further info.

![oreonengine ij error screenshot 1](https://user-images.githubusercontent.com/409304/44941286-0d2ee980-ad4f-11e8-99fd-3a8b895a4c37.png)
![oreonengine ij error screenshot 2](https://user-images.githubusercontent.com/409304/44941287-1029da00-ad4f-11e8-9adc-1b489ba4d8cf.png)

**Comment by oreonengine** [comment]
when you start the demo, there is an initial output in the console: the graphics device and the queue families of the system. What is the output for you there?

**Comment by aromanelli** [comment]
@oreonengine Here's the output from a run (see file).  The app runs, and you see the water and Sun, with no glitches/studders. If you didn't look at the console, you'd think everything was running fine.

Do note that there are multiple continuous errors being displayed in the log.  I ended up manually closing the app to get the console output to stop rolling along.  I opened this ticket just on the first error outputted to the console, and not for any follow-up errors output.

My OS is Ubuntu Budgie 18.04.1 LTS (64-bit), using Gnome 3.28.2.  Processor is Intel Core i7 CPU 980 @ 3.33GHz x 12, with 24GB RAM.  I'm using a GigaBytte GeForce GTX 1050 OC Edition, with 2GB GDDR5 (PCIe/SSE2).  Its a DirectX 12 ready card, and is six months old.

[oreonengine console output.txt](https://github.com/oreonengine/oreon-engine/files/2342583/oreonengine.console.output.txt)

**Comment by oreonengine** [comment]
Alright thank you, this is a warning by Vulkan. I guess the selected queue family capabilities does not match the use cases the engine needs. It works correctly since the the pipeline barrier (vkCmdPipelineBarrier) is skipped but not even needed by your device. The GTX 1050 is fast enough that the pipeline barriers are not even triggered. However, for slow devices this can be critical and should be fixed.

**Comment by oreonengine** [comment]
Please go to VkGUI class starting at line 133 where fonts image is loaded.:
```
VkImage fontsImage = VkImageHelper.loadImageFromFile(
	device.getHandle(), memoryProperties,
	device.getTransferCommandPool().getHandle(),
	device.getTransferQueue(),
	"gui/tex/Fonts.png",
	VK_IMAGE_USAGE_SAMPLED_BIT,
	VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
	VK_ACCESS_SHADER_READ_BIT,
	VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,
	VK_QUEUE_FAMILY_IGNORED);
```

change
```
device.getTransferCommandPool().getHandle(),
device.getTransferQueue(),
```
to 
```
device.getGraphicsCommandPool().getHandle(),
device.getGraphicsQueue(),
```
or if that doesn't help to
```
device.getComputeCommandPool().getHandle(),
device.getComputeQueue(),
```

**Comment by aromanelli** [comment]
@oreonengine Attaching two text files, with the output after each of the two changes you requested.  After each change, the errors still occurred.  I manually stopped the client in both cases after about 20-30 seconds of displaying/running.

[oreonengine getGraphicsXXX console output.txt](https://github.com/oreonengine/oreon-engine/files/2353855/oreonengine.getGraphicsXXX.console.output.txt)
[oreonengine getComputeXXX console output.txt](https://github.com/oreonengine/oreon-engine/files/2353856/oreonengine.getComputeXXX.console.output.txt)

**Comment by oreonengine** [comment]
Alright, I will go deeper into it. It is possible that I have the same erros with a Titan Xp but somehow this device doesn't outputs validation messages...
I guess somewhere I specified a commandPool from a queue family which is not compatible with the queue to which the command buffer is submitted, it should be a small fix, but I need to search for the affected command buffer(s).

**Comment by aromanelli** [comment]
@oreonengine Just to point out explicitly, I'm using the open source version of the Nvidia driver, and not the closed-source version from Nvidia itself (Ubuntu Budgie doesn't give me the option to install the closed version), so the open-sourced version may have additional error outputting to console, that the closed version does not, hence why you don't see those errors, maybe??

If there's any additional debugging help I can do for you, please feel free to reach out to me.  I'll keep monitoring this bug report page.

**Comment by civortech** [comment]
I am getting this:
C:\dev\java\oreon-engine\oreonengine\examples-vulkan\target>java -jar examples-vulkan-3.0.0.jar
Could not decode image file [ile:/C:/dev/java/oreon-engine/oreonengine/examples-vulkan/target/examples-vulkan-3.0.0.jar!/gui/tex/Fonts.png]: [Unable to open file]
Exception in thread "main" java.lang.NullPointerException
        at org.oreon.core.vk.wrapper.buffer.StagingBuffer.<init>(StagingBuffer.java:19)
        at org.oreon.core.vk.wrapper.image.VkImageHelper.loadImage(VkImageHelper.java:74)
        at org.oreon.core.vk.wrapper.image.VkImageHelper.loadImageFromFile(VkImageHelper.java:49)
        at org.oreon.vk.components.ui.VkGUI.init(VkGUI.java:133)
        at org.oreon.examples.vk.oreonworlds.VkSystemMonitor.init(VkSystemMonitor.java:24)
        at org.oreon.vk.engine.VkDeferredEngine.init(VkDeferredEngine.java:180)
        at org.oreon.examples.vk.oreonworlds.VkOreonworlds.main(VkOreonworlds.java:17)

any idea why? 
opengl example works fine tho.

**Comment by aromanelli** [comment]
@civortech 
> I am getting this:
> C:\dev\java\oreon-engine\oreonengine\examples-vulkan\target>java -jar examples-vulkan-3.0.0.jar
> **Could not decode image file [ile:/C:/dev/java/oreon-engine/oreonengine/examples-vulkan/target/examples-vulkan-3.0.0.jar!/gui/tex/Fonts.png]: [_Unable to open file_]**
> Exception in thread "main" java.lang.NullPointerException
> at org.oreon.core.vk.wrapper.buffer.StagingBuffer.(StagingBuffer.java:19)
> at org.oreon.core.vk.wrapper.image.VkImageHelper.loadImage(VkImageHelper.java:74)
> at org.oreon.core.vk.wrapper.image.VkImageHelper.loadImageFromFile(VkImageHelper.java:49)
> at org.oreon.vk.components.ui.VkGUI.init(VkGUI.java:133)
> at org.oreon.examples.vk.oreonworlds.VkSystemMonitor.init(VkSystemMonitor.java:24)
> at org.oreon.vk.engine.VkDeferredEngine.init(VkDeferredEngine.java:180)
> at org.oreon.examples.vk.oreonworlds.VkOreonworlds.main(VkOreonworlds.java:17)
> 
> any idea why?
> opengl example works fine tho.

Going off of the stacktrace only (bolded/italicized part), and not having looked at the code referenced by the stacktrace, either the .jar file is bad, or it does not have inside of it (jars are just zip files) the Fonts.png file. Another possibility is upper/lower case issues if running under Linux.

Try using zip to open the .jar file and look inside of it for the Fonts.png file, see if its there.

**Comment by civortech** [comment]
thx for response.
running on win10pro with i7 4th gen, 32gb ram and gtx1080,  jdk 8, vulkansd 1.2.154.1, netbeans 13
the resource is there:
![image](https://user-images.githubusercontent.com/40436186/124531790-37496580-dddd-11eb-8e9f-faed07a842c9.png)

seems to be an issue in org.oreon.core.vk.image VkImageLoader.decodeImage
with the stbi_load not liking the absolute path.
